nuxeo/nuxeo-platform-importer

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericThreadedImportTask.java
Minor typo fix for SUPNXP-15517.
=> Fixing typo in importer logging. Changed "Comiting" to "Committing".

nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/service/ScannedFileMapperComponent.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/110/
=> task-NXP-21378-deprecate-methods-of-fileutils

nuxeo-importer-xml-parser/src/main/java/org/nuxeo/ecm/platform/importer/xml/parser/XMLImporterServiceImpl.java, nuxeo-importer-xml-parser/src/test/java/org/nuxeo/ecm/platform/importer/xml/parser/test/TestDocUpdateWithDepotData.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/137/
=> fix-NXP-19466-field-default-value

nuxeo-importer-xml-parser/src/main/java/org/nuxeo/ecm/platform/importer/xml/parser/XMLImporterServiceImpl.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-slacoin/136/
=> fix-NXP-21508-automation-chain-parameters

nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/service/ScanFileFieldMapping.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-jmarchal/1/
=> fix-NXP-21919-hour-date-format

nuxeo-importer-scan/src/test/java/org/nuxeo/platform/scanimporter/tests/TestService.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-bstefanescu-master/13/
=> feature-NXP-19326-runtime-evols

nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/service/ScanFileFieldMapping.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-jmarchal/4/
=> fix-NXP-22091-fix-date-formatting-thread-safety

nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/service/ScanFileFieldMapping.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-jmarchal-8.10/1/
=> 8.10-HF/fix-NXP-21919-hour-date-format

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericMultiThreadedImporter.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/DefaultImporterComponent.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/DefaultImporterService.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/DefaultImporterServiceImpl.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/ImporterConfigurationDescriptor.java, nuxeo-importer-core/src/main/resources/OSGI-INF/default-importer-service.xml, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestDefaultImporterServiceWithMeta.java, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestDefaultImporterServiceWithMeta2.java, nuxeo-importer-core/src/test/resources/test-importer-service-contrib2.xml, nuxeo-importer-jaxrs/src/main/java/org/nuxeo/ecm/platform/importer/executor/jaxrs/RandomImporterExecutor.java, nuxeo-importer-jaxrs/src/main/resources/OSGI-INF/importer-service-contrib.xml, nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/processor/ScannedFileImporter.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-jroussel/3/
=> fix-NXP-22880-make-configurable-perflogging

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericMultiThreadedImporter.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/DefaultImporterComponent.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/DefaultImporterService.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/DefaultImporterServiceImpl.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/ImporterConfigurationDescriptor.java, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestDefaultImporterServiceWithMeta.java, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestDefaultImporterServiceWithMeta2.java, nuxeo-importer-core/src/test/resources/test-importer-service-contrib2.xml, nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/processor/ScannedFileImporter.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-jroussel-8.10/3/
=> fix-NXP-22880-make-configurable-perflogging-8.10

nuxeo-importer-core/pom.xml, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestImporterWithFileManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fdavid-master/315/
=> fix-NXP-23400-add-facet-directly-in-doc-type-contribution

nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/consumer/DocumentConsumerPolicyBuilder.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/message/BlobMessage.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/KafkaHelper.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/TestPatternBoundedQueuingKafka.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/TestPatternQueuingKafka.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/producer/RandomIdMessageProducerFactory.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-slacoin/178/
=> feature-NXBT-2056-kafka-test-env

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericMultiThreadedImporter.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericThreadedImportTask.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/consumer/DocumentMessageConsumer.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/311/
=> cleanup-NXP-24089-CloseableCoreSession

nuxeo-importer-xml-parser/src/main/java/org/nuxeo/ecm/platform/importer/xml/parser/AttributeConfigDescriptor.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/315/
=> cleanup-NXP-24092-code-quality

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/source/RandomTextSourceNode.java, nuxeo-importer-scan-xml-parser/src/main/java/org/nuxeo/ecm/platform/importer/xml/parser/AdvancedScannedFileFactory.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/316/
=> cleanup-NXP-24092-code-quality-2

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/executor/AbstractImporterExecutor.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/source/RandomTextSourceNode.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/318/
=> cleanup-NXP-24092-code-quality-3

nuxeo-importer-stream/src/test/resources/test-kafka-config-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-bdelbosc3/87/
=> fix-NXP-24009-kafka-test-env

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/properties/MetadataCollector.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/source/FileWithMetadataSourceNode.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/source/FileWithNonHeritedIndividalMetaDataSourceNode.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/source/RandomTextSourceNode.java, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestRandomNodes.java, nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/listener/IngestionTrigger.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/319/
=> cleanup-NXP-24092-code-quality-4

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericMultiThreadedImporter.java, nuxeo-importer-jaxrs/src/main/java/org/nuxeo/ecm/platform/importer/executor/jaxrs/AbstractJaxRSImporterExecutor.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/producer/FileBlobMessageProducer.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/producer/RandomDocumentMessageProducerFactory.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/322/
=> cleanup-NXP-24092-code-quality-5

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/properties/MetadataFile.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/378/
=> feature-NXP-24032-doc-model-trashed-api

nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/service/ScannedFileMapperComponent.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/382/
=> task-NXP-24371-remove-dreprecated-usage-commons-lang3

nuxeo-importer-xml-parser/ReadMe.md
add all available functions, add code highlighting for examples
=> NXDOC-1514 improve documentation

nuxeo-importer-scan-xml-parser/src/test/java/org/nuxeo/ecm/platform/importer/xml/parser/TestDeployment.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/393/
=> feature-NXP-24034-separate-trashed-from-lifecycle

nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/consumer/DocumentConsumerPolicyBuilder.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/message/BlobMessage.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/KafkaHelper.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/TestPatternBoundedQueuingKafka.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/TestPatternQueuingKafka.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/producer/RandomIdMessageProducerFactory.java, nuxeo-importer-stream/src/test/resources/test-kafka-config-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-bdelbosc3/94/
=> fix-NXP-24512-stream-kafka-latency-tracker-9.10

nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/producer/FileBlobMessageProducer.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/producer/RandomDocumentMessageProducerFactory.java, nuxeo-importer-stream/src/test/java/org/nuxeo/importer/stream/tests/importer/TestBlobImportKafka.java, nuxeo-importer-stream/src/test/java/org/nuxeo/importer/stream/tests/importer/TestDocumentImportKafka.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/TestPatternBoundedQueuingKafka.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/TestPatternQueuingKafka.java, nuxeo-importer-stream/src/test/resources/log4j.xml, nuxeo-importer-stream/src/test/resources/test-kafka-config-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-bdelbosc2/187/
=> feature-NXP-24641-stream-use-watermark-9.10

nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/KafkaHelper.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/477/
=> feature-NXP-25507-add-WorkManagerConfiguration

nuxeo-importer-stream/pom.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-bdelbosc2/232/
=> feature-NXP-25608-metrics

nuxeo-importer-stream/src/main/java/org/nuxeo/lib/stream/pattern/consumer/internals/AbstractCallablePool.java, nuxeo-importer-stream/src/test/java/org/nuxeo/importer/stream/tests/importer/TestAutomationKafkaNoSubscribe.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/TestPatternBoundedQueuing.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/consumer/ErrorIdMessageConsumer.java, nuxeo-importer-stream/src/test/java/org/nuxeo/lib/stream/tests/pattern/consumer/IdMessageFactory.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-bdelbosc2/234/
=> fix-NXP-25664-stream-importer-hangs

nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/processor/ScanedFileSourceNode.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/496/
=> fix-NXP-25529-sonar-fixes

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/random/HunspellDictionaryHolder.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/random/RandomTextGenerator.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/source/RandomTextSourceNode.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/500/
=> fix-NXP-25529-sonar-fixes-2

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/random/PartialTextExtractor.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/509/
=> fix-NXP-25529-sonar-fixes-3

nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/FileBlobProducers.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/RandomBlobProducers.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-2/162/
=> feature-NXP-25900-fix-system-principal

nuxeo-importer-core/pom.xml, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericThreadedImportTask.java, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestGenericThreadedImportTask.java, nuxeo-importer-core/src/test/resources/schema/documentResolver.xsd, nuxeo-importer-core/src/test/resources/test-document-resolver-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fdavid-master/528/
=> fix-NXP-25184-core-session-doc-resolver

nuxeo-importer-core/pom.xml, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericThreadedImportTask.java, nuxeo-importer-core/src/test/java/org/nuxeo/ecm/platform/importer/tests/TestGenericThreadedImportTask.java, nuxeo-importer-core/src/test/resources/schema/documentResolver.xsd, nuxeo-importer-core/src/test/resources/test-document-resolver-contrib.xml
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fdavid-9.10/35/
=> fix-NXP-25184-core-session-doc-resolver-9.10

nuxeo-importer-core/pom.xml, nuxeo-importer-jaxrs/pom.xml, nuxeo-importer-scan/pom.xml, nuxeo-importer-xml-parser/pom.xml, nuxeo-importer-xml-parser/src/main/java/org/nuxeo/ecm/platform/importer/xml/parser/XMLImporterServiceImpl.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/596/
=> feature-NXP-26495-upgrade-dom4j

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/factories/FileManagerDocumentModelFactory.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/307/
=> fix-NXP-26178-note-double-versioning

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/log/BufferredLogger.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/log/PerfLogger.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/random/RandomTextGenerator.java, nuxeo-importer-xml-parser/src/main/java/org/nuxeo/ecm/platform/importer/xml/parser/XMLImporterServiceImpl.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier/240/
=> NXP-26194-remove-stringbuffer

nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/base/GenericMultiThreadedImporter.java, nuxeo-importer-core/src/main/java/org/nuxeo/ecm/platform/importer/service/DefaultImporterComponent.java, nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/processor/ScannedFileImporter.java, nuxeo-importer-scan/src/main/java/org/nuxeo/ecm/platform/scanimporter/service/ScanFileMappingDescriptor.java, nuxeo-importer-scan/src/test/java/org/nuxeo/platform/scanimporter/tests/TestService.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/StreamImporters.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/BlobConsumers.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/DocumentConsumers.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/FileBlobProducers.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/RandomBlobProducers.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/RandomDocumentProducers.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/automation/RedisDocumentConsumers.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/consumer/BlobMessageConsumer.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/consumer/BlobWatermarkMessageConsumer.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/consumer/DocumentConsumerPool.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/consumer/DocumentMessageConsumer.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/message/BlobMessage.java, nuxeo-importer-stream/src/main/java/org/nuxeo/importer/stream/producer/RandomDocumentMessageProducerFactory.java, nuxeo-importer-stream/src/main/java/org/nuxeo/lib/stream/pattern/consumer/ConsumerPool.java, nuxeo-importer-stream/src/main/java/org/nuxeo/lib/stream/pattern/consumer/internals/ConsumerRunner.java, nuxeo-importer-stream/src/main/java/org/nuxeo/lib/stream/pattern/producer/ProducerPool.java, nuxeo-importer-stream/src/test/java/org/nuxeo/importer/stream/tests/importer/TestBlobImport.java, nuxeo-importer-stream/src/test/java/org/nuxeo/importer/stream/tests/importer/TestDocumentImport.java
Not created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-3/27/ but succeed into it
=> Improvement NXP-24952 compile with java11
